name: ci-workflow

on: [push, pull_request]

jobs:
  ubuntu-build-u18-j11-yrand-aulocal:

    timeout-minutes: 90
    runs-on: ubuntu-latest
    name: U18 J11 Yrand AuLocal

    steps:
      - name: Disk Before Code and Cache
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Check Maven Com Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/com
          key: mvn-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-com-
      - name: Check Maven Org Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org
          key: mvn-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-org-
      - name: Check Maven Net Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/net
          key: mvn-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-net-
      - name: Check Maven IO Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/io
          key: mvn-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-io-
      - name: Check Maven BIZ Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/biz
          key: mvn-biz-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-biz-
      - name: Check Maven IT Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/it
          key: mvn-it-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-it-
      - name: Set up JDK 11 EN
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Disk After Cache
        run: |
          df -h
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Djava.security.egd=file:/dev/urandom -Dmaven.surefire.arguments="-Duser.language=en -Duser.region=AU -Duser.timezone=Australia/Melbourne"
        run: |
          mvn -V -T 0.8C package verify -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff -pl -nifi-assembly,-nifi-toolkit/nifi-toolkit-assembly,-nifi-system-tests -nsu
      - name: Disk After Build
        run: |
          df -h

  ubuntu-build-u20-j11-yrand-aulocal:

    timeout-minutes: 90
    runs-on: ubuntu-20.04
    name: U20 J11 Yrand AuLocal

    steps:
      - name: Disk Before Code and Cache
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Check Maven Com Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/com
          key: mvn-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-com-
      - name: Check Maven Org Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org
          key: mvn-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-org-
      - name: Check Maven Net Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/net
          key: mvn-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-net-
      - name: Check Maven IO Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/io
          key: mvn-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-io-
      - name: Check Maven BIZ Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/biz
          key: mvn-biz-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-biz-
      - name: Check Maven IT Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/it
          key: mvn-it-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-it-
      - name: Set up JDK 11 EN
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Disk After Cache
        run: |
          df -h
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Djava.security.egd=file:/dev/urandom -Dmaven.surefire.arguments="-Duser.language=en -Duser.region=AU -Duser.timezone=Australia/Melbourne"
        run: |
          mvn -V -T 0.8C package verify -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff -pl -nifi-assembly,-nifi-toolkit/nifi-toolkit-assembly,-nifi-system-tests -nsu
      - name: Disk After Build
        run: |
          df -h

  ubuntu-build-u18-j11-yrand-nolocal:

    timeout-minutes: 90
    runs-on: ubuntu-latest
    name: U18 J11 Yrand NoLocal

    steps:
      - name: Disk Before Code and Cache
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Check Maven Com Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/com
          key: mvn-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-com-
      - name: Check Maven Org Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org
          key: mvn-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-org-
      - name: Check Maven Net Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/net
          key: mvn-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-net-
      - name: Check Maven IO Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/io
          key: mvn-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-io-
      - name: Check Maven BIZ Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/biz
          key: mvn-biz-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-biz-
      - name: Check Maven IT Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/it
          key: mvn-it-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-it-
      - name: Set up JDK 11 EN
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Disk After Cache
        run: |
          df -h
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Djava.security.egd=file:/dev/urandom
        run: |
          mvn -V -T 0.8C package verify -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff -pl -nifi-assembly,-nifi-toolkit/nifi-toolkit-assembly,-nifi-system-tests -nsu
      - name: Disk After Build
        run: |
          df -h

  ubuntu-build-u20-j11-norand-nolocal:

    timeout-minutes: 90
    runs-on: ubuntu-20.04
    name: U20 J11 Norand NoLocal

    steps:
      - name: Disk Before Code and Cache
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check NPM Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Check Maven Com Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/com
          key: mvn-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-com-
      - name: Check Maven Org Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/org
          key: mvn-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-org-
      - name: Check Maven Net Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/net
          key: mvn-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-net-
      - name: Check Maven IO Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/io
          key: mvn-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-io-
      - name: Check Maven BIZ Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/biz
          key: mvn-biz-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-biz-
      - name: Check Maven IT Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/it
          key: mvn-it-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvn-it-
      - name: Set up JDK 11 EN
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Disk After Cache
        run: |
          df -h
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN
        run: |
          mvn -V -T 0.8C package verify -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff -pl -nifi-assembly,-nifi-toolkit/nifi-toolkit-assembly,-nifi-system-tests -nsu
      - name: Disk After Build
        run: |
          df -h