name: ci-workflow

on: [push, pull_request]

jobs:
  ubuntu-build-fr:

    timeout-minutes: 90
    runs-on: ubuntu-latest
    name: Ubuntu - JDK 1.8 FR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Check NPM Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.npm
        key: nix-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          nix-npm-
    - name: Check Maven Com Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository/com
        key: nix-maven-com-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          nix-maven-com-
    - name: Check Maven Org Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository/org
        key: nix-maven-org-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          nix-maven-org-
    - name: Check Maven Net Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository/net
        key: nix-maven-net-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          nix-maven-net-
    - name: Check Maven IO Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository/io
        key: nix-maven-io-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          nix-maven-io-
    - name: Check Maven BIZ Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository/biz
        key: nix-maven-biz-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          nix-maven-biz-
    - name: Check Maven IT Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository/it
        key: nix-maven-it-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          nix-maven-it-
    - name: Set up JDK 1.8 FR
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dmaven.surefire.arguments="-Duser.language=fr -Duser.region=FR -Duser.timezone=Europe/Paris"
      run: |
        mvn -version
        mvn -T 0.8C install -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff
        rm -rf ~/.m2/repository/org/apache/nifi

  ubuntu-build-en:

    timeout-minutes: 90
    runs-on: ubuntu-latest
    name: Ubuntu - JDK 11 EN

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check NPM Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.npm
          key: nix-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nix-npm-
      - name: Check Maven Com Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/com
          key: nix-maven-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-com-
      - name: Check Maven Org Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/org
          key: nix-maven-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-org-
      - name: Check Maven Net Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/net
          key: nix-maven-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-net-
      - name: Check Maven IO Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/io
          key: nix-maven-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-io-
      - name: Check Maven BIZ Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/biz
          key: nix-maven-biz-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-biz-
      - name: Check Maven IT Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/it
          key: nix-maven-it-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-it-
      - name: Set up JDK 11 EN
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dmaven.surefire.arguments="-Duser.language=en -Duser.region=AU -Duser.timezone=Australia/Melbourne"
        run: |
          mvn -version
          mvn -T 0.8C install -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff
          rm -rf ~/.m2/repository/org/apache/nifi

  osx-build-jp:

    timeout-minutes: 90
    runs-on: macos-latest
    name: MacOS - JDK 1.8 JP

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check NPM Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.npm
          key: nix-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nix-npm-
      - name: Check Maven Com Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/com
          key: nix-maven-com-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-com-
      - name: Check Maven Org Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/org
          key: nix-maven-org-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-org-
      - name: Check Maven Net Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/net
          key: nix-maven-net-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-net-
      - name: Check Maven IO Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/io
          key: nix-maven-io-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-io-
      - name: Check Maven BIZ Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/biz
          key: nix-maven-biz-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-biz-
      - name: Check Maven IT Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository/it
          key: nix-maven-it-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            nix-maven-it-
      - name: Set up JDK 1.8 JP
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=1g -XX:+UseG1GC -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dmaven.surefire.arguments="-Duser.language=ja -Duser.region=JP -Duser.timezone=Asia/Tokyo"
        run: |
          mvn -version
          mvn -T 0.8C install -B -Pcontrib-check,include-grpc -Ddir-only -ntp -ff
          rm -rf ~/.m2/repository/org/apache/nifi

  windows-build:

    runs-on: windows-latest
    name: Windows - JDK 1.8

    steps:
      - name: Setup Git
        run:  |
          git config --global core.autocrlf false
          git config --global core.longpaths true
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check Maven Com Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~\.m2\repository\com
          key: windows-maven-com-${{ hashFiles('**\pom.xml') }}
          restore-keys: |
            windows-maven-com-
      - name: Check Maven Org Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~\.m2\repository\org
          key: windows-maven-org-${{ hashFiles('**\pom.xml') }}
          restore-keys: |
            windows-maven-org-
      - name: Check Maven Net Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~\.m2\repository\net
          key: windows-maven-net-${{ hashFiles('**\pom.xml') }}
          restore-keys: |
            windows-maven-net-
      - name: Check Maven IO Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~\.m2\repository\io
          key: windows-maven-io-${{ hashFiles('**\pom.xml') }}
          restore-keys: |
            windows-maven-io-
      - name: Check Maven BIZ Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~\.m2\repository\biz
          key: nix-maven-biz-${{ hashFiles('**\pom.xml') }}
          restore-keys: |
            nix-maven-biz-
      - name: Check Maven IT Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~\.m2\repository\it
          key: nix-maven-it-${{ hashFiles('**\pom.xml') }}
          restore-keys: |
            nix-maven-it-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Xmx2g -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dmaven.surefire.arguments="-Duser.language=en -Duser.region=US -Duser.timezone=US/Pacific"
        run: |
          mvn -version
          mvn -T 0.8C install -B -Ddir-only -ntp -ff
          Remove-Item -path '~\.m2\repository\org\apache\nifi' -recurse -force
